# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore /warnaserror
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Run benchmarks
      run: dotnet run --configuration Release --project tests/FluentSortingDotNet.Benchmarks 
    - name: Read benchmark results
      id: read_benchmark
      run: |
        content=$(cat tests/FluentSortingDotNet.Benchmarks/BenchmarkDotNet.Artifacts/results/*-report.md)
        echo "content<<EOF" >> $GITHUB_OUTPUT
        echo "$content" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    - name: Post benchmark comment
      if: github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ## Benchmark Results
          ${{ steps.read_benchmark.outputs.content }}
